language: python
python:
  - "3.8"
install: "pip install coverage"
script:
  - coverage run unittest_multilist.py
after_success: bash <(curl -s https://codecov.io/bash)

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Ecrypted <access-key-id>=AKIAQK67FD4VBEVWEIOF"
  secret_access_key:
    secure: "Encrypted <secret-access-key>=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"
  region: "us-east-1"
  app: " "
  env: " "
  bucket_name: " "
