name: deploy-lambda-function
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main
    - name: Deploy code to AWS Lambda
      uses: mariamrf/py-lambda-action@v1.0.0
      with:
        lambda_function_arn: 'arn:aws:lambda:us-east-2:023553449770:function:A2lambda'
        lambda_function_name: 'A2lambda'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-2'
